version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --region ${aws_region} --no-include-email)
      - REPOSITORY_URL=${repository_url}
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - go test
      - go build -o ${app_container_name}
      - docker build -t $REPOSITORY_URL:latest .
      - docker tag $REPOSITORY_URL:latest $REPOSITORY_URL:$IMAGE_TAG

  post_build:
    commands:
      - docker push $REPOSITORY_URL:latest
      - docker push $REPOSITORY_URL:$IMAGE_TAG
      - printf '[{"name":"${app_container_name}","imageUri":"%s"}]' $REPOSITORY_URL:$IMAGE_TAG > imagedefinitions.json
    
artifacts:
  files: imagedefinitions.json
